{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deploy-chart.fullname" . }}-config
  annotations:
    checksum/configmap: {{ .Values.configMap.data | toJson | sha256sum }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
