{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deploy-chart.fullname" . }}-secret
  annotations:
    checksum/secret: {{ .Values.secret.data | toJson | sha256sum }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
