{{- include "deploy-chart.validatePDB" . -}}
{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: {{ include "deploy-chart.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "deploy-chart.fullname" . }}
  labels:
    {{- include "deploy-chart.labels" . | nindent 4 }}
    {{- with .Values.podDisruptionBudget.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.podDisruptionBudget.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  {{- with .Values.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "deploy-chart.selectorLabels" . | nindent 6 }}
{{- end }}
