{{- include "stardew-valley-server.validateValues" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stardew-valley-server.fullname" . }}
  labels:
    {{- include "stardew-valley-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "stardew-valley-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "stardew-valley-server.checksumAnnotations" . | nindent 8 }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "stardew-valley-server.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "stardew-valley-server.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      containers:
        - name: stardew-server
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "stardew-valley-server.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: game
              containerPort: {{ .Values.gameServer.gamePort }}
              protocol: {{ .Values.service.protocol }}
          envFrom:
            - secretRef:
                name: {{ include "stardew-valley-server.fullname" . }}-secret
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            {{- omit .Values.startupProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.persistence.gameData.enabled }}
            - name: game-data
              mountPath: /data/Stardew
            {{- end }}
            {{- if .Values.persistence.serverConfig.enabled }}
            - name: server-config
              mountPath: /config/xdg/config/StardewValley
            {{- end }}
      volumes:
        {{- if .Values.persistence.gameData.enabled }}
        - name: game-data
          persistentVolumeClaim:
            claimName: {{ include "stardew-valley-server.fullname" . }}-game-data
        {{- end }}
        {{- if .Values.persistence.serverConfig.enabled }}
        - name: server-config
          persistentVolumeClaim:
            claimName: {{ include "stardew-valley-server.fullname" . }}-server-config
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
