{{- include "stardew-valley-server.validateValues" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stardew-valley-server.fullname" . }}-secret
  labels:
    {{- include "stardew-valley-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  STEAM_USER: {{ .Values.gameServer.steamCredentials.username | quote }}
  STEAM_PASS: {{ .Values.gameServer.steamCredentials.password | quote }}
  {{- if .Values.gameServer.steamCredentials.guardCode }}
  STEAM_GUARD_CODE: {{ .Values.gameServer.steamCredentials.guardCode | quote }}
  {{- end }}
  {{- if .Values.gameServer.vncPassword }}
  VNC_PASSWORD: {{ .Values.gameServer.vncPassword | quote }}
  {{- end }}
  DISABLE_RENDERING: {{ .Values.gameServer.disableRendering | default "true" | quote }}
