apiVersion: v1
kind: Service
metadata:
  name: {{ include "stardew-valley-server.fullname" . }}
  labels:
    {{- include "stardew-valley-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  ports:
    - port: {{ .Values.service.gamePort }}
      targetPort: game
      protocol: {{ .Values.service.protocol }}
      name: game
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "stardew-valley-server.selectorLabels" . | nindent 4 }}
